### ISSUE TITLE
Worker dies causing celery to restart but not accepting any subsequent jobs

### ISSUE THREAD

**Issue by vincentiusmartin** [vincentiusmartin/QBiC-Pred#7]
```
[2019-03-07 17:33:49,211: WARNING/ForkPoolWorker-4:1] Processing Mus_musculus|M02182_1.94d|Badis09|Sox1_2631.2=v2

 -------------- celery@rapid-926.vm.duke.edu v4.2.0 (windowlicker)
---- **** -----
--- * ***  * -- Linux-4.4.0-142-generic-x86_64-with-Ubuntu-16.04-xenial 2019-03-07 15:30:12
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         app:0x7f9a933e69e8
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery


[tasks]
  . app.controller.celerytask.do_prediction
  . app.controller.celerytask.drop_index
  . app.controller.celerytask.inittbl


Restarting celery worker (/home/rapiduser/QBiC-Pred/website/venv/bin/celery worker -A app.celery --loglevel=info)
[2019-03-07 17:33:59,838: ERROR/MainProcess] Process 'ForkPoolWorker-4' pid:49235 exited with 'exitcode 70'
[2019-03-07 17:33:59,861: ERROR/MainProcess] Process 'ForkPoolWorker-2' pid:49233 exited with 'exitcode 70'
[2019-03-07 17:33:59,925: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: exitcode 70.',)
Traceback (most recent call last):
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 322, in start
    blueprint.start(self)
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 598, in start
    c.loop(*c.loop_args())
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/celery/worker/loops.py", line 80, in asynloop
    raise WorkerShutdown(should_stop)
celery.exceptions.WorkerShutdown: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/billiard/pool.py", line 1223, in mark_as_worker_lost
    human_status(exitcode)),
billiard.exceptions.WorkerLostError: Worker exited prematurely: exitcode 70.
[2019-03-07 17:34:02,207: INFO/MainProcess] Connected to redis://localhost:6379/0
[2019-03-07 17:34:02,217: INFO/MainProcess] mingle: searching for neighbors
[2019-03-07 17:34:03,237: INFO/MainProcess] mingle: all alone
[2019-03-07 17:34:03,245: INFO/MainProcess] celery@rapid-926.vm.duke.edu ready.
10.197.205.89 - - [08/Mar/2019 13:19:46] "GET / HTTP/1.1" 200 -
10.197.205.89 - - [08/Mar/2019 13:19:46] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 -
10.197.205.89 - - [08/Mar/2019 13:19:46] "GET /static/js/index.js HTTP/1.1" 200 -
10.197.205.89 - - [08/Mar/2019 13:19:46] "GET /static/css/bootstrap-select.min.css HTTP/1.1" 304 -
10.197.205.89 - - [08/Mar/2019 13:19:46] "GET /static/css/base.css HTTP/1.1" 304 -
10.197.205.89 - - [08/Mar/2019 13:19:46] "GET /static/js/jquery-3.3.1.min.js HTTP/1.1" 304 -
10.197.205.89 - - [08/Mar/2019 13:19:46] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 -
10.197.205.89 - - [08/Mar/2019 13:19:46] "GET /static/js/bootstrap-select.min.js HTTP/1.1" 304 -
10.197.205.89 - - [08/Mar/2019 13:19:46] "GET /static/js/base.js HTTP/1.1" 304 -
10.197.205.89 - - [08/Mar/2019 13:19:46] "GET /static/css/index.css HTTP/1.1" 304 -
10.197.205.89 - - [08/Mar/2019 13:19:46] "GET /static/images/headerlogo.png HTTP/1.1" 304 -
10.197.205.89 - - [08/Mar/2019 13:19:46] "GET /static/images/mut1.jpeg HTTP/1.1" 304 -
10.197.205.89 - - [08/Mar/2019 13:19:46] "GET /static/css/luthier-regular.ttf HTTP/1.1" 304 -
10.197.205.89 - - [08/Mar/2019 13:19:46] "GET /static/images/footer.png HTTP/1.1" 304 -
10.197.205.89 - - [08/Mar/2019 13:19:46] "GET /static/images/mut3.png HTTP/1.1" 304 -
10.197.205.89 - - [08/Mar/2019 13:19:46] "GET /recent HTTP/1.1" 200 -
10.197.205.89 - - [08/Mar/2019 13:19:46] "GET /static/images/mut2.jpg HTTP/1.1" 304 -
10.197.205.89 - - [08/Mar/2019 13:19:48] "GET /process/6f6a30bc-0adb-43de-98a1-2661f80365aa HTTP/1.1" 200 -
10.197.205.89 - - [08/Mar/2019 13:19:48] "GET /static/css/result.css HTTP/1.1" 200 -
10.197.205.89 - - [08/Mar/2019 13:19:48] "GET /static/js/result.js HTTP/1.1" 304 -
10.197.205.89 - - [08/Mar/2019 13:19:48] "GET /recent HTTP/1.1" 200 -
10.197.205.89 - - [08/Mar/2019 13:19:48] "GET /getinputparam/6f6a30bc-0adb-43de-98a1-2661f80365aa HTTP/1.1" 200 -
10.197.205.89 - - [08/Mar/2019 13:19:50] "GET /status/6f6a30bc-0adb-43de-98a1-2661f80365aa?parent-1=6f6a30bc-0adb-43de-98a1-2661f80365aa&parent-0=06b29397-3acb-4ff9-b447-279cf3ae4a85 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rapiduser/QBiC-Pred/website/app/views/result.py", line 351, in task_status
    'current': task.info.get('current', 0),
AttributeError: 'WorkerLostError' object has no attribute 'get'
10.197.205.89 - - [08/Mar/2019 13:20:05] "GET / HTTP/1.1" 200 -
```

**Comment by vincentiusmartin** [comment]
A different error:
```
[2019-03-12 13:16:32,810: ERROR/ForkPoolWorker-4] Task app.controller.celerytask.do_prediction[f9acc01f-ca69-4158-9aab-8c6dd9eb5841] raised unexpected: MemoryError()
Traceback (most recent call last):
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/rapiduser/QBiC-Pred/website/app/controller/celerytask.py", line 309, in do_prediction
    res = [p.get() for p in async_pools]
  File "/home/rapiduser/QBiC-Pred/website/app/controller/celerytask.py", line 309, in <listcomp>
    res = [p.get() for p in async_pools]
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/billiard/pool.py", line 1742, in get
    raise self._value.exception
MemoryError
[2019-03-12 13:16:32,930: ERROR/MainProcess] Pool callback raised exception: MemoryError('Process got: ',)
Traceback (most recent call last):
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/billiard/pool.py", line 1747, in safe_apply_callback
    fun(*args, **kwargs)
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/celery/worker/request.py", line 544, in on_success
    return self.on_failure(retval, return_ok=True)
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/celery/worker/request.py", line 347, in on_failure
    raise MemoryError('Process got: %s' % (exc_info.exception,))
MemoryError: Process got: 
198.86.29.21 - - [12/Mar/2019 13:49:35] "GET / HTTP/1.1" 200 -
```

**Comment by vincentiusmartin** [comment]
```
[2019-03-15 09:14:09,852: ERROR/MainProcess] Process 'ForkPoolWorker-1' pid:69305 exited with 'signal 9 (SIGKILL)'
[2019-03-15 09:14:09,876: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL).',)
Traceback (most recent call last):
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/billiard/pool.py", line 1223, in mark_as_worker_lost
    human_status(exitcode)),
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL).
[2019-03-15 09:14:10,407: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/redis/connection.py", line 392, in read_response
    raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 322, in start
    blueprint.start(self)
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 598, in start
    c.loop(*c.loop_args())
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/kombu/transport/redis.py", line 1040, in on_readable
    self.cycle.on_readable(fileno)
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/kombu/transport/redis.py", line 714, in _brpop_read
    **options)
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File "/home/rapiduser/QBiC-Pred/website/venv/lib/python3.5/site-packages/redis/connection.py", line 403, in read_response
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)
```

**Comment by vincentiusmartin** [comment]
```
69312:M 15 Mar 09:11:51.655 # Client id=14 addr=[::1]:34764 fd=19 name= age=103 idle=7 flags=N db=0 sub=5 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=88 oll=1 omem=35530895 events=r cmd=unsubscribe scheduled to be closed ASAP for overcoming of output buffer limits.
^C69312:signal-handler (1552657644) Received SIGINT scheduling shutdown...
```
